from qiskit import QuantumCircuit

circuito = QuantumCircuit(5, 5)
circuito.x(0)
circuito.h(1)
circuito.cx(2, 3)
circuito.x(4)
circuito.h(0)
circuito.x(1)
circuito.h(2)
circuito.cx(3, 4)
circuito.x(0)
circuito.h(1)
circuito.cx(2, 3)
circuito.h(4)
circuito.x(0)
circuito.h(1)
circuito.cx(2, 3)
circuito.x(4)
circuito.h(0)
circuito.cx(1, 2)
circuito.x(3)
circuito.h(4)
circuito.x(0)
circuito.h(1)
circuito.cx(2, 3)
circuito.measure([0, 1, 2, 3, 4], [0, 1, 2, 3, 4])
