spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: default1

custom:
  cpg:
    url: http://localhost:3333
    volumes: ./src/main/resources/qcpg/uploads
